### ISSUE TITLE
Does this work with Docker swarm mode?

### ISSUE THREAD

**Issue by riker09** [chaifeng/ufw-docker#1]
If so, how? I have a service with multiple published ports and I have no idea how configure UFW at this point.

On a single Docker node this little helper works fine, btw. :slightly_smiling_face:

**Comment by chaifeng** [comment]
No, this script doesn't support docker swarm mode now. But I have an idea to implement this feature. 

The core point is to run a special service in global mode:
- Bind its network to host, this allows managing host firewall rules inside a container.
- Monitor events of docker swarm, update firewall rules when docker swarm services changed.

I'm not sure what kind of unknown problems we might encounter, just an idea. I will try it when I have time soon.

**Comment by riker09** [comment]
Sounds promising. Good luck writing that service. I had to give up on ufw and dig into iptables. You may close this ticket, if you like.
