### ISSUE TITLE
rationale for choosing networks

### ISSUE THREAD

**Issue by pniederlag** [chaifeng/ufw-docker#10]
Hi,

https://github.com/chaifeng/ufw-docker/blob/2545d2977baae9e51ce256d4d9a0043a78a1ca33/ufw-docker#L294

what is the rationale behind the chosen networks? 
This does work in most cases but might need adaption in certain cases?

For example I have changed the address-pool in my docker start file like so:

      --default-address-pool=base=10.120.0.0/16,size=24 

So its seems I was just lucky enough to see ufw-docker working due to picking a network that is part of the default setup. 

Would be nice to mention this somewhere and have some way to change the networks so `ufw-docker check` and `ufw-docker install ` would fit an adapted docker setup.

**Comment by pniederlag** [comment]
Well, lesson learned. :->

This is the full range of all A,B und C-class private networks as definde by the IETF/IANA https://en.wikipedia.org/wiki/Private_network

At least in my use cases I do join some private wireless networks in different locations. And I'd really like to make sure my ufw/firewall does block requests from the wifi and only allow traffic originating on my development-machine itself.

So, I just adapt the network(s) to whatever seems reasonable to me.

Thx for putting up ufw-docker anyway!

**Comment by chaifeng** [comment]
Just an assumption.

[ufw-docker/README.md at master · chaifeng/ufw-docker](https://github.com/chaifeng/ufw-docker/blob/master/README.md#how-it-works)
> The following rules allow the private networks to be able to visit each other. Normally, private networks are more trusted than public networks.
>
>      -A DOCKER-USER -j RETURN -s 10.0.0.0/8
>      -A DOCKER-USER -j RETURN -s 172.16.0.0/12
>      -A DOCKER-USER -j RETURN -s 192.168.0.0/16

**Comment by chaifeng** [comment]
Yes, it still makes sense to restrict access from certain internal networks
