### ISSUE TITLE
Deny outgoing connections from containers

### ISSUE THREAD

**Issue by e-dorigatti** [chaifeng/ufw-docker#12]
Thank you for this great repo. I want to prevent containers to connect to certain IP addresses, i.e. I want `ufw deny out to <dest>` to stop connections from containers to dest. I tried with `ufw route deny out on docker0 to <dest>`, but it does not work. I also tried to change the interface to `eth0` and all other interfaces I have, but connections are still allowed. These are all the related rules I have currently:

```
<dest>                DENY OUT    Anywhere
<dest> on docker0     DENY FWD    Anywhere
<dest> on eth0        DENY FWD    Anywhere
<dest> on lo          DENY FWD    Anywhere
<dest> on veth4ca42e2 DENY FWD    Anywhere
<dest> on vethe1dfed2 DENY FWD    Anywhere
```

This blocks pings from the host, but not from docker containers.

**Comment by chaifeng** [comment]
Hi

Currently, the firewall rules allow all connections from docker containers. In the `DOCKER-USER` chain:

    -A DOCKER-USER -s 10.0.0.0/8 -j RETURN
    -A DOCKER-USER -s 172.16.0.0/12 -j RETURN
    -A DOCKER-USER -s 192.168.56.128/28 -j RETURN
    -A DOCKER-USER -p udp -m udp --sport 53 --dport 1024:65535 -j RETURN
    -A DOCKER-USER -j ufw-user-forward
    // ......
    -A DOCKER-USER -j RETURN

The first three lines allow all connections from docker containers. The block rules added by ufw exist in the `ufw-user-forward` chain, which is the fifth rule. So the connections from docker containers never reach that rule.

We have TWO options:
* OPTION one:
> Modify `/etc/ufw/after.rules`, move the rule `-A DOCKER-USER -j ufw-user-forward` in the DOCKER-USER to be the first.
> Using the command to block connections to the `1.2.3.4`
>>     ufw route deny from any to 1.2.3.4
* OPTION two:
> Using iptables add block rule at the beginning of the `DOCKER-USER` chain. For example:
>>     iptables -I DOCKER-USER -j REJECT -d 1.2.3.4

**Comment by chaifeng** [comment]
I am considering whether to make the first option permanent.

**Comment by e-dorigatti** [comment]
Thank you very much for your answer, option 1 works fine and I think it would be a good addition to your repo. Just for the record, my ugly and hacky solution was to block from within the container: `docker exec $id iptables -A FORWARD -j DROP -v -d 1.2.3.4`.
