### ISSUE TITLE
Not working from container to host

### ISSUE THREAD

**Issue by bitwombat** [chaifeng/ufw-docker#16]
I'm trying to access a service running on the host from a container.
I'm testing with `nc -l 9900` on the host, and `nc 172.18.0.1 9900` in the container.
It works with ufw disabled.
It doesn't work with ufw enabled. Here is the DOCKER-USER chain:

```
$ sudo iptables -L DOCKER-USER
Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  10.0.0.0/8           anywhere
RETURN     all  --  172.16.0.0/12        anywhere
RETURN     all  --  192.168.0.0/16       anywhere
RETURN     udp  --  anywhere             anywhere             udp spt:domain dpts:1024:65535
ufw-user-forward  all  --  anywhere             anywhere
DROP       tcp  --  anywhere             192.168.0.0/16       tcp flags:FIN,SYN,RST,ACK/SYN
DROP       tcp  --  anywhere             10.0.0.0/8           tcp flags:FIN,SYN,RST,ACK/SYN
DROP       tcp  --  anywhere             172.16.0.0/12        tcp flags:FIN,SYN,RST,ACK/SYN
DROP       udp  --  anywhere             192.168.0.0/16       udp dpts:0:32767
DROP       udp  --  anywhere             10.0.0.0/8           udp dpts:0:32767
DROP       udp  --  anywhere             172.16.0.0/12        udp dpts:0:32767
RETURN     all  --  anywhere             anywhere
```

That looks to me like it should work. Which means the RETURN lines aren't matching for some reason? If I look through all of `iptables -L`, I don't see 172.16 mentioned anywhere else.

Ubuntu 18.04.3.
Docker 18.09.7

Any ideas?

**Comment by bitwombat** [comment]
Just confirmed this on a brand-new installation...

**Comment by chaifeng** [comment]
You need `iptables -L -t nat` to see the nat table. 

You just use UFW to manage the ports opened on your servers. This tool is used for managing ports published with containers. This case is, a container listens on a port, and this port is published on your server.

Your solution is right. If you want containers to access a `9900` service running on the host, use:

    ufw allow from 172.16.0.0/12 to any port 9900
    # or, depends on the network range you are using
    ufw allow from 10.0.0.0/8 to any port 9900

Thanks!

**Comment by bitwombat** [comment]
Cool, thanks for the help @chaifeng
