### ISSUE TITLE
Block specific ip from accessing port 443

### ISSUE THREAD

**Issue by n8tb1t** [chaifeng/ufw-docker#17]
I have a service on port 443,
How I can block specific IP from accessing port 443

I tried this:

`ufw insert 1 deny from 89.179.6.129 to any port 443`
`iptables -A INPUT -s 89.179.6.129 -p tcp --destination-port 443 -j DROP`

the user can still access the service exposed with:

`ufw route allow proto tcp from any to any port 443`

thanks for the help?

**Comment by chaifeng** [comment]
If the command allows the service to be exposed to all IPs.

    ufw route allow proto tcp from any to any port 443

Then you can use the following command to deny a certain IP to access this service.

    ufw route insert 1 deny proto tcp from 89.179.6.129 to any port 443
