### ISSUE TITLE
How to drop access for the port 80 on eth0 ? in /etc/ufw/after.rules

### ISSUE THREAD

**Issue by Inv0k-er** [chaifeng/ufw-docker#18]
I readed your post. But I don't understand how I can to drop access for the port 80 on eth0 (I have docker. Docker work in 80 port) ? in /etc/ufw/after.rules

**Comment by chaifeng** [comment]
Have you tried the tool [ufw-docker](https://github.com/chaifeng/ufw-docker#ufw-docker-util)?

    ufw-docker install

this command will put the following rules to the end of file `/etc/ufw/after.rules`

    # BEGIN UFW AND DOCKER
    *filter
    :ufw-user-forward - [0:0]
    :DOCKER-USER - [0:0]
    -A DOCKER-USER -j RETURN -s 10.0.0.0/8
    -A DOCKER-USER -j RETURN -s 172.16.0.0/12
    -A DOCKER-USER -j RETURN -s 192.168.0.0/16

    -A DOCKER-USER -p udp -m udp --sport 53 --dport 1024:65535 -j RETURN

    -A DOCKER-USER -j ufw-user-forward

    -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 192.168.0.0/16
    -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 10.0.0.0/8
    -A DOCKER-USER -j DROP -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 172.16.0.0/12
    -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 192.168.0.0/16
    -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 10.0.0.0/8
    -A DOCKER-USER -j DROP -p udp -m udp --dport 0:32767 -d 172.16.0.0/12

    -A DOCKER-USER -j RETURN
    COMMIT
    # END UFW AND DOCKER

After restarting `ufw` service, it will block access for all running containers from outside.

Then using

    ufw-docker allow your-container-name 443

to allow the port that you want to publish, for example, port 443.
