### ISSUE TITLE
How to block outgoing traffic from container

### ISSUE THREAD

**Issue by riker09** [chaifeng/ufw-docker#2]
I have a container which is listening on port 80. But I don't want the container to be able to establish connections to this port. Or any other port for that matter. Is this the right place to ask this question? Sorry if it is not, I'm rather new to Docker, UFW and TCP security.

**Comment by go2null** [comment]
why not stop the container from listening?

**Comment by chaifeng** [comment]
Sure, you can ask any questions here. But I cannot get your points. Do you mean that you don’t want this container establishes connections to itself? Could you explain it more?

**Comment by riker09** [comment]
I've solved the issues I had with my setup by learning iptables. So I actually don't need this solution anymore. But for what it's worth, it seems like a nice approach to a complex topic.

Anyway, what I meant was the container is publishing port 80, so incoming connections on that port should be allowed for obvious reasons (in iptables terms: DPT=80 must be allowed). My concern and the reason for asking was that the container should not establish connections to port 80 by itself. DPT=80 is okay for INCOMING connections, but should not be allowed for OUTGOING connections.

I solved it with two iptables rules where the first targets the incoming interface:

```
# Accept packets to (d)estination port 80 coming in from eth0
iptables -A MYCHAIN -i eth0 -m tcp -p tcp --dport 80 -j ALLOW

# Allow packets for established connections going out to (s)ource port 80
iptables -A MYCHAIN -m tcp -p tcp --sport 80 -m state --state ESTABLISHED -j ALLOW
```

I think my original issue was when using ufw the outgoing traffic was not blocked for new connections. An attacker that manages to control a container can "phone home" (steal your data, load more malware, ...)
