### ISSUE TITLE
ERROR: UFW is disabled or you are not root user

### ISSUE THREAD

**Issue by babaz8** [chaifeng/ufw-docker#26]
Even everything is running and enable I keep on receiving this error so the script is not usable
● ufw.service - Uncomplicated firewall
   Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sun 2020-01-05 13:56:12 CET; 6min ago
     Docs: man:ufw(8)
  Process: 9017 ExecStart=/lib/ufw/ufw-init start quiet (code=exited, status=0/SUCCESS)
 Main PID: 9017 (code=exited, status=0/SUCCESS)

gen 05 13:56:12 CORNERWS systemd[1]: Starting Uncomplicated firewall...
gen 05 13:56:12 CORNERWS ufw-init[9017]: Firewall already started, use 'force-reload'
gen 05 13:56:12 CORNERWS systemd[1]: Started Uncomplicated firewall.

**Comment by chaifeng** [comment]
I guess it's because of language environments.

Could you show me the output of the command `sudo ufw status`? and the value of environments `LANG`, `LC_ALL`
