### ISSUE TITLE
Docker can access internet after: ufw default deny outgoing

### ISSUE THREAD

**Issue by JohanMollevik** [chaifeng/ufw-docker#32]
I am trying to create a jailed machine to prevent the docker containers run there from accessing internet other than whitelisted hosts.

To that end i tried to use
ufw default deny outgoing

I found this bug report https://github.com/chaifeng/ufw-docker/issues/12 and have applied the first option described there but it still does not prevent outgoing commections.

I thested this by running (image downloaded earlier)
docker -it debian:buster bash
 $ apt-get update

and the image still could access the apt servers.

Is there any solution to fix this using ufw-docker or do I have to bite the bullet and use raw iptables?

**Comment by chaifeng** [comment]
Just released a new version.

Using `ufw route deny from <containers-ip-cidr> to any` to block connections from containers.
