### ISSUE TITLE
Constant literal 172.16.0.x / docker0 network --> auto-detect

### ISSUE THREAD

**Issue by jcward** [chaifeng/ufw-docker#35]
On my various Ubuntu 20.04 systems, the default `docker0` network seems to be `172.17.0.1/16`, while this script is hard-coded to `172.16.0.0/12`

I've seen other sources suggest finding this via:

```
ip addr show docker0
```

Or grabbing the host address via:

```
HOST_IP=$(ip addr show docker0 | grep "inet " | awk '{print $2}' | awk -F/ '{print $1}')
# 172.17.0.1
```

**Comment by chaifeng** [comment]
Thanks for your comment.

The networks `172.17.0.0/16`, `10.0.0.0/8`, and `192.168.0.0/16` are reserved private networks, see [RFC1918](https://tools.ietf.org/html/rfc1918). And those rules are added to `DOCKER-USER` chain, only available to docker. So we can use these networks safely.
