### ISSUE TITLE
Feature request: Automate ufw rules with docker engine?

### ISSUE THREAD

**Issue by shinebayar-g** [chaifeng/ufw-docker#36]
Hi, I've been a huge fan of this script for a while now. One thing that boggles my mind is it's pretty manual and it could be improved.
For example this [nginx-proxy ](https://github.com/nginx-proxy/nginx-proxy) software runs as regular docker image and updates nginx rules as needed based on other docker image's ENVs. It solves manual rule update issue and less error prone.
I think it maybe possible to follow similar approach. For example, ufw-docker-agent will run as regular docker container on the host and will be connected to docker socket. It'll update ufw rules based on new container's ENVs. Containers should run with special ENVs if we want to expose them to public internet. like: `docker run -d -e UFW_ALLOW_PORT=80 nginx`

Another example is [Traefik](https://doc.traefik.io/traefik/providers/docker/). Traefik runs as regular container on the host and connected to docker socket. It scans new containers to see if it includes special "labels" and updates its rules based on container labels.

Does anyone think such implementation is possible?

**Comment by aadrian** [comment]
@shinebayar-g

> it's pretty manual and it could be improved.

+1

> For example, ufw-docker-agent will run as regular docker container on the host

-1 
IMHO it's not an "optimal" approach the requirement to have a running docker container, just for the firewall to work properly.

> Containers should run with special ENVs if we want to expose them to public internet. like: `docker run -d -e UFW_ALLOW_PORT=80 nginx`

+1


> Another example is Traefik. 

Traefik is nice, but it's an overkill for many situations. 


> Does anyone think such implementation is possible?

It should be, but it would be a "workaround" . I'm still surprised that Docker or UFW didn't fixed this issue yet :( .

**Comment by shinebayar-g** [comment]
> IMHO it's not an "optimal" approach the requirement to have a running docker container, just for the firewall to work properly.

It doesn't matter really, as long as service can connect to docker socket and listen to docker api events.

> Traefik is nice, but it's an overkill for many situations.

It's just example application of how they handles things.

> It should be, but it would be a "workaround" . I'm still surprised that Docker or UFW didn't fixed this issue yet :( .

Docker stated that they won't "fix".

**Comment by shinebayar-g** [comment]
Okay, I hacked together some code and got working code. If someone wants to use it reply here.
