### ISSUE TITLE
Dns packets are dropped by 50%

### ISSUE THREAD

**Issue by arkanoid87** [chaifeng/ufw-docker#4]
By adding those rules I had 50% change to get dns answers from an upsteam dns server.

How to reproduce.

- start a dnsmasq container that forwards all queries to 1.1.1.1 or 8.8.8.8
- shell into dnsmasq container
- dig www.google.com @127.0.0.1

You have 50% chance to get an answer and 50% chance to have a timeout

tcpdump from the host says that answer from upstream (1.1.1.1 or 8.8.8.8) is correctly received

By flushing the DOCKER-USER table the problem is gone

**Comment by chaifeng** [comment]
Hi @arkanoid87 

Thanks for reporting this issue.

For now, you can run the following commands to fix it temporarily:

    sudo iptables -I DOCKER-USER 4 -p udp -s 8.8.8.8 -j RETURN
    sudo iptables -I DOCKER-USER 4 -p udp -s 1.1.1.1 -j RETURN

I'll update this issue soon if I found the reason. Thanks!

**Comment by chaifeng** [comment]
Fixed. 

Sorry for my late reply, I'm a bit busy in recent weeks.

From dnsmasq's manual page, as it explains:

>     --min-port=<port>
>         Do not use ports less than that given as source for outbound DNS queries. Dnsmasq picks random ports  as
>         source  for  outbound queries: when this option is given, the ports used will always to larger than that
>         specified. Useful for systems behind firewalls. If not specified, defaults to 1024.

Dnsmasq doesn't use the default port range of our host. Because DNS is a very common service, so I added a rule to allow DNS packages by default.

Anyway, we can use the follow command to allow DNS service:

    ufw route allow proto udp from any port 53 to any port 1024:65535
