### ISSUE TITLE
Is there any way to get rid of it?

### ISSUE THREAD

**Issue by Foreist** [chaifeng/ufw-docker#44]
Is there a way to go back to before installing ufw-docker?

**Comment by chaifeng** [comment]
Yes.

1. `sudo vim /etc/ufw/after.rules`, remove all the lines from `# BEGIN UFW AND DOCKER` to `# END UFW AND DOCKER`.
2. Restart UFW service or reboot your server

or disable it temporarily by running the command `sudo iptables -I DOCKER-USER 1 -j RETURN` without reboot or restart ufw service.

**Comment by Foreist** [comment]
thx
