### ISSUE TITLE
[Question] Exposing host ports

### ISSUE THREAD

**Issue by amura11** [chaifeng/ufw-docker#48]
First of all thank you for creating this guide. Running into this problem and trying to find a good solution is very challenging as many other sources say to disable Dockers IPTables support which doesn't seem like a good solution. Having a good explanation of what you're trying to achieve and how it works is very helpful.

I want to have my server setup so that when I run `ufw allow 80` that opens the hosts port 80 not the containers. Reading the **The reason for choosing ufw-user-forward, not ufw-user-input** section it seems like I could use `ufw-user-input` instead to achieve this but I'm not sure if that is correct.

**My Qeuestion**: If I use `ufw-user-input` will that mean that when I run a command like `ufw allow 80` that would allow external connections to the service running on port 80 and not the any containers running on 80?

_Edit_

For clarity, I have my container setup using `-p 8080:80` and I have Nginx running on the host forwarding external requests on port 80 to port 8080. I don't want anyone externally to be able to access 8080 directly, only port 80.

**Comment by chaifeng** [comment]
In short, using `ufw-user-input` and `ufw allow 80` together will make all instances with a container port of 80 to be public, regardless of which host ports that they are published to.

**Comment by flavienbwk** [comment]
> In short, using `ufw-user-input` and `ufw allow 80` together will make all instances with a container port of 80 to be public, regardless of which host ports that they are published to.

How to make it so port 8080 ONLY is exposed ? (published port)
