### ISSUE TITLE
Rules need to re-entered after container restart

### ISSUE THREAD

**Issue by itchy2** [chaifeng/ufw-docker#54]
Hi all,

after restarting a container (docker-compose down, docker-compose up) I need to re-enter the rules.

Any Ideas how to fix this?

Thanks and kind regards
Itchy2

**Comment by chaifeng** [comment]
Please check out this project https://github.com/shinebayar-g/ufw-docker-automated

a wrapper of ufw-docker to monitor services of docker compose.

**Comment by itchy2** [comment]
Thanks a lot. Thats a brilliat hint. I don't know the relationship / background of the different projects. Maybe it makes sense to reference this project in the Readme?
