### ISSUE TITLE
ufw-docker-agent not working in a docker swarm

### ISSUE THREAD

**Issue by stuffinator** [chaifeng/ufw-docker#60]
Hi, I'm trying to get this working in my swarm, but I'm failing with the ufw-docker-agent image.

I have everything set up and run the command `ufw-docker service allow <my_service> <port>`. The script now tries to create the ufw-docker-agent service and run it on every node. 

However, it fails on every node with the message:
> ERROR: UFW is disabled or you are not root user

To further analyze the problem I cloned this repository, altered the Dockerfile slightly, built my own image and then ran it. After that I ran the bash command within the container with `docker exec -it <container_id> bash` so I can troubleshoot from within the container.

Even though I'm logged in as root in the container, running the command `ufw status` returns the following error
> ERROR: problem running iptables: iptables v1.8.4 (legacy): can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

Am I doing something wrong or did something brake at some point?

**Comment by chaifeng** [comment]
Hi, which ubuntu version are you using? Is it an older one?

**Comment by stuffinator** [comment]
The one in the dockerfile here.

https://github.com/chaifeng/ufw-docker/blob/8aecb89d4e12a5b2573bd452b537c75e6039a9e9/Dockerfile#L1

**Comment by stuffinator** [comment]
So far I found that if I add `--cap-add NET_ADMIN` to the following command
https://github.com/chaifeng/ufw-docker/blob/2b4a44ff7a4afaaa63fa33784fc9f355b766f750/ufw-docker#L200-L206

I don't have permission problems anymore, but it still doesn't work, because ufw is not automatically enabled. That means I still get 

> ERROR: UFW is disabled or you are not root user

And I haven't found a clean way of enabling ufw within the container.

**Comment by chaifeng** [comment]
I don't think we can enable/disable UFW of host from inside containers

**Comment by stuffinator** [comment]
No that's not what I want. But it's fine I got ufw enabled within the container.

I'm currently progressing from one hurdle to the next and I don't understand how it ever worked in a docker swarm setup.

I've illustrated the workflow and where I'm currently stuck at.

![Untitled Diagram drawio](https://user-images.githubusercontent.com/26797810/145709405-c4fd63d0-3e60-48f4-ad3e-a215458f6316.png)

How is the container supposed to read the iptable rules of the host? The `DOCKER-INGRESS` rules are only on the host, not in the container.

Again any help would be appreciated.

**Comment by stuffinator** [comment]
Nevermind, I created my own custom solution.

**Comment by Yamakasi** [comment]
@stuffinator can you tell us what you created ?

**Comment by stuffinator** [comment]
@Yamakasi 
I created a script similar to ufw-docker, but focused on my use-case. When I execute `myscript allow <service_name>` it creates/updates a ufw application profile for the service and then runs a temporary docker container with host network access. Within the container runs another script that simply executes `ufw route allow <profile_name>` via ssh on all swarm nodes.

The user behind the ssh access can only run two commands `ufw route allow *` and `ufw route delete allow *`. He has no rights for anything else.

**Comment by Yamakasi** [comment]
@stuffinator That sounds nice, did you share it somewhere ?

**Comment by Yamakasi** [comment]
@stuffinator any updates about your made script ?

**Comment by stuffinator** [comment]
Sorry the script is not in any public repository, simply because it is very static and focused on my infrastructure solution. If I were to make it publicly available I'd have to clean it up, make it more dynamic, fix some things and write an explanation on how it's set up and how it works.

This would require some time investment that I currently just can't afford.

If I get around to do it at some point, I'll let you know. But don't expect anything any time soon.

**Comment by Yamakasi** [comment]
@stuffinator Thanks for the update!

Maybe you can tell me how you detect what to open for swarm services as this isn't that easy it seems. I can't get it from the scope.

**Comment by di-rect** [comment]
@stuffinator did you had any time yet to get something going, would be great to see!
