### ISSUE TITLE
Docker Swarm port mode: host not reachable

### ISSUE THREAD

**Issue by Flusinerd** [chaifeng/ufw-docker#66]
Hello. I want to allow access to my traefik that is published using
in docker swarm
```
- published: 80
   target: 80
   mode: host
```

I am able to reach the traefik instance localy on the node using for example
```
curl localhost
```

But I cannot reach it from the outside

I tried to open port 80 using
```
sudo ufw allow http
```

or using 
```
sudo ufw-docker service allow traefik_traefik 80
```
But it seems like the routing does not work properly?

In the ufw-logs it does not say that it has been blocked.

When running a simple netcat on port 80 on the host machine and using the normal UFW command, I am able to reach it from the outside.

**Comment by binaryfire** [comment]
@Flusinerd Hi. Just wondering if you solved this? I’m having the same issue when trying to use the host network with:

```
networks:
   hostnet:
      external:
        name: host
```

Everything works as expected with UFW disabled so it’s something to do with the routing.
