### ISSUE TITLE
ufw-docker status error!

### ISSUE THREAD

**Issue by shellcompute** [chaifeng/ufw-docker#7]
Hi friends:

I got an error as follows, after installed ufw-docker and run `ufd-docker status`...
```
/usr/local/bin/ufw-docker: line 276: files_to_be_deleted[@]: unbound variable
```
My linux version is: `Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-100-generic x86_64)`
And the bash version: `GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)`

Any comment would be appreciated. Thanks!

**Comment by chaifeng** [comment]
Hi @shellcompute 

I need more output to find out the reason. Please run `ufw-docker` with debug enabled

    DEBUG=true ufw-docker ....
    # or
    sudo DEBUG=true ufw-docker ...

Thanks

**Comment by chaifeng** [comment]
Sorry, @shellcompute. I didn't notice that you are using Ubuntu 14.04. This script doesn't support this version of Ubuntu.

**The reason is that `UFW` doesn't support `forward` chain on Ubuntu 14.04/14.10/15.04!**

You can fix this docker security issue by adding the following rules to the file `/etc/ufw/after.rules`

    # BEGIN UFW AND DOCKER
    *filter
    :DOCKER-USER - [0:0]
    -A DOCKER-USER -j RETURN -s 10.0.0.0/8
    -A DOCKER-USER -j RETURN -s 172.16.0.0/12
    -A DOCKER-USER -j RETURN -s 192.168.0.0/16
    
    -A DOCKER-USER -p udp -m udp --sport 53 --dport 1024:65535 -j RETURN
        
    -A DOCKER-USER -j DROP -d 192.168.0.0/16 -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN
    -A DOCKER-USER -j DROP -d 10.0.0.0/8 -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN
    -A DOCKER-USER -j DROP -d 172.16.0.0/12 -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN
    -A DOCKER-USER -j DROP -d 192.168.0.0/16 -p udp -m udp --dport 0:32767
    -A DOCKER-USER -j DROP -d 10.0.0.0/8 -p udp -m udp --dport 0:32767
    -A DOCKER-USER -j DROP -d 172.16.0.0/12 -p udp -m udp --dport 0:32767
    
    -A DOCKER-USER -j RETURN
    COMMIT
    # END UFW AND DOCKER

**Comment by shellcompute** [comment]
Thanks a lot! @chaifeng , that solved my problem!
I've modified the ufw/after.rules, reloaded ufw, and run `ufw route allow proto tcp from any to [docker-ip] port [docker-port]` to enable "ALLOW FWD",  now it works quite well on my Ubuntu 14.04. 
Good job! It feels great to make everything under control :)

**Comment by yohanyflores** [comment]
Maybe it helps  https://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u
